export const BASE_API_URL: string = 'http://localhost:8081/api/v1';
export const PRODUCTS_URL: string = BASE_API_URL + '/products';
export const TAGS_URL: string = BASE_API_URL + '/tags';
export const CART_URL: string = BASE_API_URL + '/cart';
export const PRODUCT_AUTOCOMPLETE_URL: string = BASE_API_URL + '/products/autocomplete';
export const USER_URL: string = BASE_API_URL + '/user';
export const SESSION_URL: string = BASE_API_URL + '/session';
export const ADMIN_USER_DETAIL_URL: string = BASE_API_URL + '/admin/user';
export const ADMIN_USER_ROLE_LIST: string = BASE_API_URL + '/admin/roles';