// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hotsauceshop/ent/cartitems"
	"hotsauceshop/ent/inventory"
	"hotsauceshop/ent/tag"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InventoryCreate is the builder for creating a Inventory entity.
type InventoryCreate struct {
	config
	mutation *InventoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ic *InventoryCreate) SetName(s string) *InventoryCreate {
	ic.mutation.SetName(s)
	return ic
}

// SetDescription sets the "description" field.
func (ic *InventoryCreate) SetDescription(s string) *InventoryCreate {
	ic.mutation.SetDescription(s)
	return ic
}

// SetShortDescription sets the "shortDescription" field.
func (ic *InventoryCreate) SetShortDescription(s string) *InventoryCreate {
	ic.mutation.SetShortDescription(s)
	return ic
}

// SetSlug sets the "slug" field.
func (ic *InventoryCreate) SetSlug(s string) *InventoryCreate {
	ic.mutation.SetSlug(s)
	return ic
}

// SetPrice sets the "price" field.
func (ic *InventoryCreate) SetPrice(f float32) *InventoryCreate {
	ic.mutation.SetPrice(f)
	return ic
}

// SetSpiceRating sets the "spiceRating" field.
func (ic *InventoryCreate) SetSpiceRating(i int) *InventoryCreate {
	ic.mutation.SetSpiceRating(i)
	return ic
}

// SetNillableSpiceRating sets the "spiceRating" field if the given value is not nil.
func (ic *InventoryCreate) SetNillableSpiceRating(i *int) *InventoryCreate {
	if i != nil {
		ic.SetSpiceRating(*i)
	}
	return ic
}

// SetCreatedAt sets the "createdAt" field.
func (ic *InventoryCreate) SetCreatedAt(t time.Time) *InventoryCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (ic *InventoryCreate) SetNillableCreatedAt(t *time.Time) *InventoryCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updatedAt" field.
func (ic *InventoryCreate) SetUpdatedAt(t time.Time) *InventoryCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (ic *InventoryCreate) SetNillableUpdatedAt(t *time.Time) *InventoryCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (ic *InventoryCreate) AddTagIDs(ids ...int) *InventoryCreate {
	ic.mutation.AddTagIDs(ids...)
	return ic
}

// AddTags adds the "tags" edges to the Tag entity.
func (ic *InventoryCreate) AddTags(t ...*Tag) *InventoryCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ic.AddTagIDs(ids...)
}

// AddCartItemIDs adds the "cartItems" edge to the CartItems entity by IDs.
func (ic *InventoryCreate) AddCartItemIDs(ids ...int) *InventoryCreate {
	ic.mutation.AddCartItemIDs(ids...)
	return ic
}

// AddCartItems adds the "cartItems" edges to the CartItems entity.
func (ic *InventoryCreate) AddCartItems(c ...*CartItems) *InventoryCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ic.AddCartItemIDs(ids...)
}

// Mutation returns the InventoryMutation object of the builder.
func (ic *InventoryCreate) Mutation() *InventoryMutation {
	return ic.mutation
}

// Save creates the Inventory in the database.
func (ic *InventoryCreate) Save(ctx context.Context) (*Inventory, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InventoryCreate) SaveX(ctx context.Context) *Inventory {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InventoryCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InventoryCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InventoryCreate) defaults() {
	if _, ok := ic.mutation.SpiceRating(); !ok {
		v := inventory.DefaultSpiceRating
		ic.mutation.SetSpiceRating(v)
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := inventory.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := inventory.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InventoryCreate) check() error {
	if _, ok := ic.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Inventory.name"`)}
	}
	if _, ok := ic.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Inventory.description"`)}
	}
	if _, ok := ic.mutation.ShortDescription(); !ok {
		return &ValidationError{Name: "shortDescription", err: errors.New(`ent: missing required field "Inventory.shortDescription"`)}
	}
	if _, ok := ic.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Inventory.slug"`)}
	}
	if _, ok := ic.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Inventory.price"`)}
	}
	if _, ok := ic.mutation.SpiceRating(); !ok {
		return &ValidationError{Name: "spiceRating", err: errors.New(`ent: missing required field "Inventory.spiceRating"`)}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Inventory.createdAt"`)}
	}
	return nil
}

func (ic *InventoryCreate) sqlSave(ctx context.Context) (*Inventory, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InventoryCreate) createSpec() (*Inventory, *sqlgraph.CreateSpec) {
	var (
		_node = &Inventory{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(inventory.Table, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt))
	)
	if value, ok := ic.mutation.Name(); ok {
		_spec.SetField(inventory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ic.mutation.Description(); ok {
		_spec.SetField(inventory.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ic.mutation.ShortDescription(); ok {
		_spec.SetField(inventory.FieldShortDescription, field.TypeString, value)
		_node.ShortDescription = value
	}
	if value, ok := ic.mutation.Slug(); ok {
		_spec.SetField(inventory.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := ic.mutation.Price(); ok {
		_spec.SetField(inventory.FieldPrice, field.TypeFloat32, value)
		_node.Price = value
	}
	if value, ok := ic.mutation.SpiceRating(); ok {
		_spec.SetField(inventory.FieldSpiceRating, field.TypeInt, value)
		_node.SpiceRating = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(inventory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(inventory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := ic.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   inventory.TagsTable,
			Columns: inventory.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.CartItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   inventory.CartItemsTable,
			Columns: inventory.CartItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cartitems.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InventoryCreateBulk is the builder for creating many Inventory entities in bulk.
type InventoryCreateBulk struct {
	config
	err      error
	builders []*InventoryCreate
}

// Save creates the Inventory entities in the database.
func (icb *InventoryCreateBulk) Save(ctx context.Context) ([]*Inventory, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Inventory, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InventoryCreateBulk) SaveX(ctx context.Context) []*Inventory {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InventoryCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InventoryCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
