INSERT INTO tags (name, description, slug) VALUES ('Habanero', 'Made with fiery habanero peppers known for their fruity flavor and intense heat', 'habanero');
INSERT INTO tags (name, description, slug) VALUES ('Jalapeño', 'Contains mild to medium jalapeño peppers with a bright, green flavor', 'jalapeno');
INSERT INTO tags (name, description, slug) VALUES ('Ghost Pepper', 'Features the extremely hot ghost pepper (bhut jolokia) for serious heat seekers', 'ghost-pepper');
INSERT INTO tags (name, description, slug) VALUES ('Carolina Reaper', 'Contains the world''s hottest pepper with fruity notes and extreme heat', 'carolina-reaper');
INSERT INTO tags (name, description, slug) VALUES ('Chipotle', 'Made with smoked jalapeños for a rich, smoky flavor profile', 'chipotle');
INSERT INTO tags (name, description, slug) VALUES ('Garlic', 'Enhanced with garlic for a savory, aromatic dimension', 'garlic');
INSERT INTO tags (name, description, slug) VALUES ('Lime', 'Features tangy lime for a citrus kick that brightens the heat', 'lime');
INSERT INTO tags (name, description, slug) VALUES ('Mango', 'Blended with sweet mango for a tropical fruit balance', 'mango');
INSERT INTO tags (name, description, slug) VALUES ('Pineapple', 'Contains pineapple for a sweet and tangy tropical flavor', 'pineapple');
INSERT INTO tags (name, description, slug) VALUES ('Cayenne', 'Made with bright, pungent cayenne peppers with medium-high heat', 'cayenne');
INSERT INTO tags (name, description, slug) VALUES ('Scotch Bonnet', 'Features fruity scotch bonnet peppers known for Caribbean flavor', 'scotch-bonnet');
INSERT INTO tags (name, description, slug) VALUES ('Serrano', 'Contains crisp, bright serrano peppers with clean heat', 'serrano');
INSERT INTO tags (name, description, slug) VALUES ('Vinegar-Based', 'Uses vinegar as a primary ingredient for tanginess and preservation', 'vinegar-based');
INSERT INTO tags (name, description, slug) VALUES ('Fermented', 'Crafted using fermentation for complex, tangy flavors', 'fermented');
INSERT INTO tags (name, description, slug) VALUES ('Honey', 'Sweetened with honey for a natural sweetness that balances heat', 'honey');
INSERT INTO tags (name, description, slug) VALUES ('Tomato', 'Contains tomato for a rich base and slight sweetness', 'tomato');
INSERT INTO tags (name, description, slug) VALUES ('Apple', 'Features apple for a subtle sweetness and fruity undertone', 'apple');
INSERT INTO tags (name, description, slug) VALUES ('Onion', 'Enhanced with onion for savory depth and complexity', 'onion');
INSERT INTO tags (name, description, slug) VALUES ('Ginger', 'Contains ginger root for a warm, spicy dimension', 'ginger');
INSERT INTO tags (name, description, slug) VALUES ('Cilantro', 'Features fresh cilantro for a bright, herbal note', 'cilantro');
INSERT INTO tags (name, description, slug) VALUES ('Mustard', 'Incorporates mustard for a tangy, pungent flavor profile', 'mustard');
INSERT INTO tags (name, description, slug) VALUES ('Carrot', 'Blended with carrot for natural sweetness and body', 'carrot');
INSERT INTO tags (name, description, slug) VALUES ('Tequila', 'Contains tequila for a distinctive boozy kick and agave notes', 'tequila');
INSERT INTO tags (name, description, slug) VALUES ('Turmeric', 'Features turmeric for an earthy flavor and golden color', 'turmeric');
INSERT INTO tags (name, description, slug) VALUES ('Tamarind', 'Made with tamarind for a sweet-sour tropical complexity', 'tamarind');