// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Inventory is the predicate function for inventory builders.
type Inventory func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
